// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20220423043840_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Activities")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkSystem")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Activities = "hiking, horseback riding, snowshoeing",
                            Name = "Yellowstone",
                            ParkSystem = "National",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            Activities = "hiking, camping, astronomy",
                            Name = "Black Canyon of the Gunnison",
                            ParkSystem = "National",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 3,
                            Activities = "hiking, sight-seeing, living history",
                            Name = "Staunton State Park",
                            ParkSystem = "State",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 4,
                            Activities = "fishing, swimming, kayaking",
                            Name = "Huntsville State Park",
                            ParkSystem = "State",
                            State = "Texas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
